#index:
#    path: /
#    controller: App\Controller\DefaultController::index

prenoms:
    path: /
    defaults: {_controller: 'App\Controller\PrenomController::index'}

resultat:
    path: /resultat
    defaults: {_controller: 'App\Controller\ResultatController::index'}

cherchenom:
    path: /bonus
    defaults: {_controller: 'App\Controller\CherchenomController::index'}

searchprenom:
    path: /search
    defaults: {_controller: 'App\Controller\CherchenomController::searchPrenom'}